### ISSUE TITLE
师傅留个联系方式呗

### ISSUE THREAD

**Issue by gcxtx01** [yangbh/xproxy#1]

**Comment by yangbh** [comment]
有啥问题吗？
如果是这个project的话，有更好的替代
开个http proxy，proxy来源用https://github.com/fate0/getproxy

**Comment by gcxtx01** [comment]
不是项目,想和师傅聊一下java安全方面的东西.不知道方不方便价格qq或者v信.


原始邮件
***@***.***
***@***.***
***@***.***; ***@***.***
发送时间:2021年9月15日(周三) 11:28
主题:Re: [yangbh/xproxy] 师傅留个联系方式呗 (#1)


有啥问题吗？
 如果是这个project的话，有更好的替代
 开个http proxy，proxy来源用https://github.com/fate0/getproxy
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangbh** [comment]
> 不是项目,想和师傅聊一下java安全方面的东西.不知道方不方便价格qq或者v信. 原始邮件 ***@***.*** ***@***.*** ***@***.***; ***@***.*** 发送时间:2021年9月15日(周三) 11:28 主题:Re: [yangbh/xproxy] 师傅留个联系方式呗 (#1) 有啥问题吗？ 如果是这个project的话，有更好的替代 开个http proxy，proxy来源用https://github.com/fate0/getproxy — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

wxid_q9t44xseungz22

**Comment by gcxtx01** [comment]
师傅 你发的是微信id,加不上,加我的呗微信 gcxtx2011、qq 842533643 .


原始邮件
***@***.***
***@***.***
***@***.***; ***@***.***
发送时间:2021年9月16日(周四) 10:02
主题:Re: [yangbh/xproxy] 师傅留个联系方式呗 (#1)


不是项目,想和师傅聊一下java安全方面的东西.不知道方不方便价格qq或者v信. 原始邮件 @.*** @.*** @.; @. 发送时间:2021年9月15日(周三) 11:28 主题:Re: [yangbh/xproxy] 师傅留个联系方式呗 (#1) 有啥问题吗？ 如果是这个project的话，有更好的替代 开个http proxy，proxy来源用https://github.com/fate0/getproxy — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
wxid_q9t44xseungz22
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
